### ISSUE TITLE
Calculate monthly instead of yearly top topic contributions

### ISSUE THREAD

**Issue by sabjoslo** [BabakHemmatian/Gay_Marriage_Corpus_Study#20] opened 2018-02-11 18:14 UTC
See title.

**Comment by BabakHemmatian** [comment] 2018-02-11 19:21
Seems to me like a duplicate of topic #15 . I assigned you to that topic instead. Also you don't need to be the only person assigned to all the upcoming issues. I can help a bit :)

**Closed as completed by BabakHemmatian** 2018-02-11 19:21 UTC
